config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'
  devise_for :users
  
  resources :boards do
    resources :comments, only: [:create, :destroy]
  end
  
  get 'search', to: 'homes#search', via: [:get, :post]

end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  
  has_many :comments, dependent: :delete_all
  has_many :board_tags, dependent: :delete_all
  has_many :tags, through: :board_tags
  
  
  validates :name, presence: true, length: { maximum: 10 }
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/board_tag.rb
class BoardTag < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board
  
  validates :name, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 300 }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :board_tags, dependent: :delete_all
  has_many :boards, through: :board_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
         
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  
  
  validates :name, presence: true, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  
  def set_search
    @q = Board.includes(:comments).ransack(params[:q])
  end
  
  
  protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  
  
  def index
    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @boards = @boards.page(params[:page])
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to @board, notice: 'スレッドを新規作成しました'
    else
      flash.now[:alert] = 'スレッドの作成に失敗しました'
      render :new
    end
  end
  
  def show
    @comment = Comment.new(board_id: @board.id)
  end

  def update
    if @board.update(board_params)
      redirect_to @board, notice: '編集内容を保存しました'
    else
      flash.now[:alert] = '編集内容の保存に失敗しました'
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: 'スレッドを削除しました'
  end
  

  private

    def board_params
      params.require(:board).permit(:name, :title, :body, tag_ids: [])
    end
    
    def set_board
      @board = Board.find(params[:id])
    end
    
    def ensure_correct_user
      unless current_user.id == @board.user_id
        flash[:alert] = '権限がありません'
        redirect_back(fallback_location: request.referer)
      end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save 
      flash[:notice] = 'コメントを投稿しました'
    else
      flash[:alert] = '投稿に失敗しました'
    end
    redirect_back(fallback_location: request.referer)
  end
  
  
  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to comment.board, notice: 'コメントが削除されました'
  end
  
  private
    
    def comment_params
      params.require(:comment).permit(:name, :content, :board_id)
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def search
    @q = Board.includes(:comments).search(search_params)
    @boards = @q.result(distinct: true).page(params[:page])
  end
  
  
  private
  
    def search_params
        params.require(:q).permit(:title_or_comments_content_cont)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
    <% board.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(board.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_for board do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  
  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  
  <%= f.submit '保存', class: 'btn btn-primary form-control text-center' %>
  
<% end %>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>スレッド編集</h1>
  <div class="ml-auto boards-link">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    <% if current_user.id == @board.user_id %>
      <td><%= link_to '削除', @board, class: 'btn btn-danger', method: :delete %></td>
    <% end %>
  </div>
</div>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>スレッド一覧</h1>
  <div class="ml-auto boards-link">
    <%= form_tag boards_path, method: :get, class: 'boards-search' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み',
                       class: 'form-control boards-select',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
    <a href="/boards/new" class="btn btn-outline-dark">新規作成</a>
  </div>
</div>
<table class="table table-hover boards-table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= board.name %></td>
        <td><%= board.created_at.to_s(:datetime_jp) %></td>
        <td><%= board.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to '詳細', board, class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @boards %>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards-link">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards-link">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    <%= link_to '編集', edit_board_path(@board), class: 'btn btn-outline-dark' %>
  </div>
</div>

<%= render @board %>

<div class="comment-list">
  <div class="comment-listTitle">コメント</div>
  <%= render @board.comments %>
</div>


<%= render 'comments/form', comment: @comment, board: @board %>

app/views/comments/_comment.html.erb
  <div class="comment-item">
  <p><%= simple_format(comment.content) %></p>
  <div class="comment-bottom">
    <span><%= comment.name %></span>
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
    <% if user_signed_in? %>
      <% if current_user.id == comment.user_id %>
        <span><%= link_to '削除', board_comment_path(comment.board_id, comment.id), method: :delete, data: { confirm: '削除してよろしいですか？' } %></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="form-wrapper">
  <p class="form-title">コメント記入</p>
  <%= form_for comment, url: board_comments_path(board) do |f| %>
  
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :board_id %>
    <div class="form-group">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content, 'コメント' %>
      <%= f.text_area :content, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary form-control text-center' %>
  <% end %>
</div>

app/views/homes/index.html.erb
<h1>ようこそ5chへ！！</h1>
<p>このサイトは好きなテーマについて自由にスレッドを立てて、話し合うことができる掲示板サイトです。</p>
<p>さあ、自分の興味のあるテーマのスレッドを探してみよう！</p>
<%= link_to 'スレッド一覧へ', boards_path, class: 'btn btn-primary' %>

app/views/homes/search.html.erb
<h3>スレッド検索結果</h3><br />
<% if @boards.empty? %>
  <p><%= "#{params[:q][:title_or_comments_content_cont]}  に一致する検索結果は見つかりませんでした" %></p><br />
  <p><%= "検索のヒント:" %></p><br />
  <ul>
    <li><%= "キーワードに誤字・脱字がないか確認します。"%></li>
    <li><%= "別のキーワードを試してみます。"%></li>
  </ul>
<% else %>
  <p><%= "#{@boards.total_count}件の検索結果があります" %></p>
<% end %>

<hr class="my-4">

<% @boards.each do |board| %>
  <p><%= board.title %></p>
  <p><%= link_to '詳細', board, class: 'btn btn-primary' %></p>
<% end %>

<%= paginate @boards, class: "paginate" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- header -->
     <%= render 'shared/header' %>
    <!-- フラッシュメッセージ部分 -->
    <% flash.each do |key, value| %>
        <% key = "alert alert-primary" if key == "notice" %>
        <% key = "alert alert-danger" if key == "alert" %>
        <%= content_tag(:div, value, class: "#{key}") %>
     <% end %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
     <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light shadow mb-5" style="background-color: white">
  <a class="navbar-brand" href="#">5ch_clone</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'ホーム', root_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'スレッド一覧', boards_path %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete  %>
        </li>
        <% if current_user.try(:admin?) %>
          <li>
            <%= link_to "管理画面", "/admin" %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to '新規登録', new_user_registration_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログイン', new_user_session_path %>
        </li>
      <% end %>
    </ul>
      <dl class="searchbox mr-auto">
        <%= search_form_for @q, url: search_path do |f| %>
          <dt><%= f.text_field :title_or_comments_content_cont, placeholder: '検索ワードを入力...' %></dt>
          <dd><%= f.submit "検索" , class: 'my-2 my-sm-0 btn btn-primary search-btn'%></dd>
        <% end %>
      </dl>
  </div>
</nav>